#!/bin/sh
### BEGIN INIT INFO
# Provides:          initscript-mountp4
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     S
# Default-Stop:
# Short-Description: imx6 board startup script
### END INIT INFO

export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

if [ ! -d /mnt/mmcblk2p4 ]; then
    mkdir -p /mnt/mmcblk2p4
fi

mount /dev/mmcblk2p4 /mnt/mmcblk2p4  >> /dev/null 2>&1
if [ $? -eq 0 ];then
    exit 0
else
    mkfs.ext4 /dev/mmcblk2p4  >> /dev/null 2>&1
    mount /dev/mmcblk2p4 /mnt/mmcblk2p4  >> /dev/null 2>&1
    rm -rf /mnt/mmcblk2p4/lost+found
fi
